WebApp/Models/ViewModels/GridCollectionItemViewModel.cs
namespace WebApp.Models.ViewModels
{
    public class GridCollectionItemViewModel
    {
        public string Id { get; set; } = null!;
        public string ImageUrl { get; set; } = null!;
        public string Title { get; set; } = null!;
        public decimal Price { get; set; }
    }
}

WebApp/Models/ViewModels/GridCollectionViewModel.cs
namespace WebApp.Models.ViewModels;

public class GridCollectionViewModel
{
    public string Title { get; set; } = "";
    public IEnumerable<string> Categories { get; set; } = null!;
    public IEnumerable<GridCollectionItemViewModel> GridItems { get; set; } = null!;
    public bool LoadMore { get; set; } = false;
}

WebApp/Models/ViewModels/LoginViewModel.cs
namespace WebApp.Models.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; } = null!;
        public string Password { get; set; } = null!;
        public bool RememberMe { get; set; } = false;

    }
}

WebApp/Models/ViewModels/RegisterViewModel.cs
using WebApp.Models.Entities;

namespace WebApp.Models.ViewModels
{
    public class RegisterViewModel
    {
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string Password { get; set; } = null!;
        public string StreetName { get; set; } = null!;
        public string PostalCode { get; set; } = null!;
        public string City { get; set; } = null!;

        public static implicit operator UserEntity(RegisterViewModel model)
        {
            return new UserEntity
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                UserName = model.Email,
            };
        }

        public static implicit operator AddressEntity(RegisterViewModel model)
        {
            return new AddressEntity
            {
                StreetName = model.StreetName,
                PostalCode = model.PostalCode,
                City = model.City,
            };
        }
    }
}

WebApp/Models/ViewModels/ShowcaseViewModel.cs
namespace WebApp.Models.ViewModels;

public class ShowcaseViewModel
{
    public string? Ingress { get; set; } 
    public string? Title { get; set; } 
    public string? LinkUrl { get; set; } 
    public string? LinkContent { get; set; }
    public string? ImageUrl { get; set; } 
    public LinkButtonViewModel Button { get; internal set; }
}

WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Repositories;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {

        private readonly ContactFormRepository _formRepository;

        public ContactsController(ContactFormRepository formRepository)
        {
            _formRepository = formRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel viewModel)
        {
            if (ModelState.IsValid) 
            {
                await _formRepository.AddAsync(viewModel);
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
    }
}

WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Services;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{

    public class LoginController : Controller
    {
        private readonly AuthenticationService _authenticationService;

        public LoginController(AuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (await _authenticationService.LoginAsync(viewModel))
                    return RedirectToAction("Index", "Home");
                
                ModelState.AddModelError("", "Incorrect email or password");
            }
            return View(viewModel);
        }
    }
}

WebApp/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Helpers.Services;
using WebApp.Models.Entities;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<UserEntity> _userManager;
        private readonly AuthenticationService _authenticationService;

        public RegisterController(UserManager<UserEntity> userManager, AuthenticationService authenticationService)
        {
            _userManager = userManager;
            _authenticationService = authenticationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegisterViewModel viewModel)
        {
            if (ModelState.IsValid) 
            {
                if (await _userManager.Users.AnyAsync(x => x.Email != viewModel.Email))
                   
                {
                    if (await _authenticationService.RegisterAsync(viewModel))                     return RedirectToAction("Index", "Login");
                } 

                ModelState.AddModelError("", "User with the same mail address already exists");
            }
            return View(viewModel);
        }
    }
}

WebApp/Views/Partials/_ContactForm.cshtml
@model ContactFormViewModel


<form asp-action="Index" asp-controller="Contacts" method="post" novalidate>
    <div asp-validation-summary=ModelOnly class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="Name" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
        <span asp-validation-for="Email" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Message" class="form-label">Message</label>
        <textarea asp-for="Message" class="form-control" onkeyup="validateText(event)"></textarea> 
        <span asp-validation-for="Message" class="small text-danger"></span>
    </div>
  

    <div class="d-grid">
        <button type="submit" class="btn-success">SUBMIT</button>
    </div>
</form>

WebApp/Views/Partials/_Footer.cshtml
<footer>
    <div class="container">
        © @DateTime.Now.Year Copyright bmerketo.
    </div>
</footer>

WebApp/Views/Partials/_GridCollection.cshtml
@model GridCollectionViewModel

@if (Model != null) {
    <section class="grid-collection">
        <div class="container">
            @if (!string.IsNullOrEmpty(Model.Title))
            {
                <h1 class="title">@Model.Title</h1>
            }

            @if (Model.Categories != null)
            {
                <ul class="categories">
                    @foreach (var category in Model.Categories)
                    {
                        <li class="category-item">@category</li>
                    }
                </ul>
            }

            @if (Model.GridItems != null)
            {
                <div class="grid">
                    @foreach (var item in Model.GridItems)
                    {
                        <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                    }
                </div>
            }

            @if (Model.LoadMore)
            {
                <div class="load-more">
                    <button class="btn-outline-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
                </div>
            }

        </div>
    </section>
}

WebApp/Views/Partials/_GridCollectionItem.cshtml
@model GridCollectionItemViewModel

<a asp-controller="products" asp-action="details" asp-route-id="@Model.Id" class="collection-item">
    <img src="@Model.ImageUrl" alt="@Model.Title">
    <div class="body">
        <div class="title">@Model.Title</div>
        <div class="info">
            <div class="price">$@Model.Price</div>
            <i class="add-cart fa-regular fa-cart-plus"></i>
        </div>
    </div>
</a>

WebApp/Views/Partials/_Header.cshtml
﻿<header>
    <div class="container">
        <div class="logo"><img src="images/logo.svg" alt="">bmerketo</div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="home" asp-action="index">HOME</a>
            <a class="link" asp-controller="products" asp-action="index">PRODUCTS</a>
            <a class="link" asp-controller="contacts" asp-action="index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="products" asp-action="index"><i class="fa-regular fa-search"></i></a>
            <a class="link" asp-controller="login" asp-action="index">Login</a>
            <a class="link" asp-controller="shopping" asp-action="chart"><i class="fa-solid fa-cart-shopping"></i></a>
            <a class="link" asp-controller="admin" asp-action="">Admin</a>
            <a class="link" asp-controller="register" asp-action="">Register</a>

        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

WebApp/Views/Partials/_Login.cshtml
@model LoginViewModel

<form asp-action="Index" asp-controller="Login" method="post" novalidate>
    <div asp-validation-summary=ModelOnly class="text-danger"></div>

    
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
        <span asp-validation-for="Email" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Password" class="form-label">Password</label>
        <input asp-for="Password" type="password" class="form-control" onkeyup="validatePassword(event)" />
        <span asp-validation-for="Password" class="small text-danger"></span>
    </div>
    

    <div class="d-grid">
        <button type="submit" class="btn-success">SUBMIT</button>
    </div>
</form>

WebApp/Views/Partials/_Register.cshtml
@model RegisterViewModel

<form asp-action="Index" asp-controller="Register" method="post" novalidate>
    <div asp-validation-summary=ModelOnly class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="FirstName" class="form-label">First Name</label>
        <input asp-for="FirstName" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="FirstName" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="LastName" class="form-label">Last Name</label>
        <input asp-for="LastName" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="LastName" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
        <span asp-validation-for="Email" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Password" class="form-label">Password</label>
        <input asp-for="Password" type="password" class="form-control" onkeyup="validatePassword(event)" />
        <span asp-validation-for="Password" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StreetName" class="form-label">Street Name</label>
        <input asp-for="StreetName" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="StreetName" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="PostalCode" class="form-label">Postal Code</label>
        <input asp-for="PostalCode" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="PostalCode" class="small text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="City" class="form-label">City</label>
        <input asp-for="City" class="form-control" onkeyup="validateText(event)" />
        <span asp-validation-for="City" class="small text-danger"></span>
    </div>

    <div class="d-grid">
        <button type="submit" class="btn-success">SUBMIT</button>
    </div>
</form>

WebApp/Views/Partials/_Showcase.cshtml
@model ShowcaseViewModel



    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="ingress">@Model?.Ingress</div>
                <div class="title">@Model?.Title</div>

                @if (!string.IsNullOrEmpty(Model?.LinkUrl) && !string.IsNullOrEmpty(Model?.LinkContent))
            {
                <a href="@Model?.LinkUrl" class="btn-theme">@Model?.LinkContent</a>
            }

        </div>
            <div class="content-image">
                <img src="@Model?.ImageUrl"" Alt="@Model?.Title">
            </div>
        </div>
    </section>